name: "Format"

on: ["push", "pull_request"]

jobs:
  format:
    name: "Stylua"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Stylua"
        uses: "JohnnyMorganz/stylua-action@v4"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          version: "latest"
          args: "--check ."
