name: "Lint"

on: ["push", "pull_request"]

jobs:
  lint:
    name: "Luacheck"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Setup"
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck

      - name: "Luacheck"
        run: "make lint"
